export interface GenTableColumnPageQuery {
  tableId?: string | string[] // 所属表ID
  name?: string // 列名称
  comment?: string // 列描述
  swaggerComment?: string // 文档描述
  type?: string // 列类型
  javaType?: string // JAVA字段名
  javaField?: string // JAVA类型
  tsType?: string // TS类型
  size?: string // 长度
  digit?: number // 小数位数
  isPk?: boolean // 主键
  isIncrement?: boolean // 自增
  isRequired?: boolean // 必填
  isLogicDeleteField?: boolean // 逻辑删除
  isVersionField?: boolean // 乐观锁
  fill?: string // 填充类型
  isEdit?: boolean // 编辑
  isList?: boolean // 列表
  isQuery?: boolean // 查询
  width?: string // 宽度
  queryType?: string // 查询方式
  component?: string // 组件
  vxeComponent?: string // Vxe组件
  dictType?: string // 字典类型
  echoStr?: string // Echo
  sortValue?: number // 排序
  enumStr?: string // 枚举
  editDefValue?: string // 默认值
  editHelpMessage?: string // 提示信息
  indexHelpMessage?: string // 列表提示信息
}

export interface GenTableColumnSaveVO {
  tableId?: string // 所属表ID
  name?: string // 列名称
  comment?: string // 列描述
  swaggerComment?: string // 文档描述
  type?: string // 列类型
  javaType?: string // JAVA字段名
  javaField?: string // JAVA类型
  tsType?: string // TS类型
  size?: string // 长度
  digit?: number // 小数位数
  isPk?: boolean // 主键
  isIncrement?: boolean // 自增
  isRequired?: boolean // 必填
  isLogicDeleteField?: boolean // 逻辑删除
  isVersionField?: boolean // 乐观锁
  fill?: string // 填充类型
  isEdit?: boolean // 编辑
  isList?: boolean // 列表
  isQuery?: boolean // 查询
  width?: string // 宽度
  queryType?: string // 查询方式
  component?: string // 组件
  vxeComponent?: string // Vxe组件
  dictType?: string // 字典类型
  echoStr?: string // Echo
  sortValue?: number // 排序
  enumStr?: string // 枚举
  editDefValue?: string // 默认值
  editHelpMessage?: string // 提示信息
  indexHelpMessage?: string // 列表提示信息
}

export interface GenTableColumnUpdateVO {
  id: string
  tableId?: string // 所属表ID
  name?: string // 列名称
  comment?: string // 列描述
  swaggerComment?: string // 文档描述
  type?: string // 列类型
  javaType?: string // JAVA字段名
  javaField?: string // JAVA类型
  tsType?: string // TS类型
  size?: string // 长度
  digit?: number // 小数位数
  isPk?: boolean // 主键
  isIncrement?: boolean // 自增
  isRequired?: boolean // 必填
  isLogicDeleteField?: boolean // 逻辑删除
  isVersionField?: boolean // 乐观锁
  fill?: string // 填充类型
  isEdit?: boolean // 编辑
  isList?: boolean // 列表
  isQuery?: boolean // 查询
  width?: string // 宽度
  queryType?: string // 查询方式
  component?: string // 组件
  vxeComponent?: string // Vxe组件
  dictType?: string // 字典类型
  echoStr?: string // Echo
  sortValue?: number // 排序
  enumStr?: string // 枚举
  editDefValue?: string // 默认值
  editHelpMessage?: string // 提示信息
  indexHelpMessage?: string // 列表提示信息
}

export interface GenTableColumnResultVO {
  echoMap?: any
  id?: string // ID
  createdTime?: string // 创建时间
  createdBy?: string // 创建人ID
  updatedTime?: string // 最后修改时间
  updatedBy?: string // 最后修改人ID
  tableId?: string // 所属表ID
  name?: string // 列名称
  comment?: string // 列描述
  swaggerComment?: string // 文档描述
  type?: string // 列类型
  javaType?: string // JAVA字段名
  javaField?: string // JAVA类型
  tsType?: string // TS类型
  size?: string // 长度
  digit?: number // 小数位数
  isPk?: boolean // 主键
  isIncrement?: boolean // 自增
  isRequired?: boolean // 必填
  isLogicDeleteField?: boolean // 逻辑删除
  isVersionField?: boolean // 乐观锁
  fill?: string // 填充类型
  isEdit?: boolean // 编辑
  isList?: boolean // 列表
  isQuery?: boolean // 查询
  width?: string // 宽度
  queryType?: string // 查询方式
  component?: string // 组件
  vxeComponent?: string // Vxe组件
  dictType?: string // 字典类型
  echoStr?: string // Echo
  sortValue?: number // 排序
  enumStr?: string // 枚举
  editDefValue?: string // 默认值
  editHelpMessage?: string // 提示信息
  indexHelpMessage?: string // 列表提示信息
}
