/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./../components/Auth/index.vue')['default']
    AuthAll: typeof import('./../components/AuthAll/index.vue')['default']
    BaseDialog: typeof import('./../components/Dialog/BaseDialog.vue')['default']
    BasicUpload: typeof import('./../components/BasicUpload/src/BasicUpload.vue')['default']
    BlocksTree: typeof import('./../components/BlocksTree/index.vue')['default']
    CodeEdite: typeof import('./../components/CodeEdite/index.vue')['default']
    Copyright: typeof import('./../components/Copyright/index.vue')['default']
    DialogFooter: typeof import('./../components/Dialog/components/DialogFooter.vue')['default']
    DialogHeader: typeof import('./../components/Dialog/components/DialogHeader.vue')['default']
    DialogWrapper: typeof import('./../components/Dialog/components/DialogWrapper.vue')['default']
    FileList: typeof import('./../components/BasicUpload/src/FileList.vue')['default']
    FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
    I18nSelector: typeof import('./../components/I18nSelector/index.vue')['default']
    IconPicker: typeof import('./../components/IconPicker/index.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    JsonPreview: typeof import('./../components/JsonPreview/JsonPreview.vue')['default']
    LayoutContainer: typeof import('./../components/LayoutContainer/index.vue')['default']
    LoginSwitcher: typeof import('./../components/LoginSwitcher/index.vue')['default']
    NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
    ThumbUrl: typeof import('./../components/BasicUpload/src/ThumbUrl.vue')['default']
    UploadDialog: typeof import('./../components/BasicUpload/src/UploadDialog.vue')['default']
    UploadPreviewDialogl: typeof import('./../components/BasicUpload/src/UploadPreviewDialogl.vue')['default']
    Vue3Cron: typeof import('./../components/vue3Cron/index.vue')['default']
  }
}
