<script setup lang="ts">

</script>

<template>
  <div>
    <PageHeader title="自定义字体" content="自定义字体需要下载字体文件，不建议在非英文环境中使用" footer="以下为框架预设字体" />
    <PageMain title="Digital 7">
      <p class="digital-7">
        admin
      </p>
      <p class="digital-7">
        1234567890,.
      </p>
    </PageMain>
    <PageMain title="Digital 7（等宽）">
      <p class="digital-7_mono">
        admin
      </p>
      <p class="digital-7_mono">
        1234567890,.
      </p>
    </PageMain>
  </div>
</template>

<style lang="scss" scoped>
@font-face {
  font-family: digital-7regular;
  src: url(@/assets/digital/digital-7-webfont.eot);
  src: url(@/assets/digital/digital-7-webfont.eot?#iefix) format("embedded-opentype"),
  url(@/assets/digital/digital-7-webfont.woff2) format("woff2"),
  url(@/assets/digital/digital-7-webfont-T.woff) format("woff"),
  url(@/assets/digital/digital-7-webfont.svg#digital-7regular) format("svg");
  font-weight: 400;
  font-style: normal
}

/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on January 22, 2021 */
@font-face {
  font-family: digital-7_monomono;
  src: url(@/assets/digital/digital-7_mono-webfont-p3QHBSNF.eot);
  src: url(@/assets/digital/digital-7_mono-webfont-p3QHBSNF.eot?#iefix) format("embedded-opentype"),
  url(@/assets/digital/digital-7_mono-webfont.woff2) format("woff2"),
  url(@/assets/digita/digital-7_mono-webfont.woff) format("woff"),
  url(@/assets/digita/digital-7_mono-webfont.svg#digital-7_monomono) format("svg");
  font-weight: 400;
  font-style: normal
}

.digital-7,.digital-7_mono {
  margin: 10px 0;
  font-size: 48px
}

.digital-7 {
  font-family: digital-7regular
}

.digital-7_mono {
  font-family: digital-7_monomono
}
</style>
